import approvalDemoXml from "../../samples/approval-demo.bpmn?raw";

const baseNodeDetails = {
  StartEvent_Submit: {
    nodeId: "StartEvent_Submit",
    nodeName: "提交申请",
    nodeTypeLabel: "开始事件",
    runtimeStateLabel: "已完成",
    runtimeStateClass: "is-completed",
    ownerLabel: "系统",
    activatedAt: "2026-04-23 14:50:01",
    completedAt: "2026-04-23 14:50:01",
    definitionRows: [
      { label: "触发方式", value: "按钮触发" },
      { label: "按钮来源", value: "申请打印" },
    ],
    events: [
      {
        title: "流程启动",
        actor: "系统通知",
        time: "2026-04-23 14:50:01",
        message: "由业务按钮触发流程实例创建。",
      },
    ],
  },
  Task_Manager: {
    nodeId: "Task_Manager",
    nodeName: "经理审批",
    nodeTypeLabel: "人工审批",
    runtimeStateLabel: "已完成",
    runtimeStateClass: "is-completed",
    ownerLabel: "李经理",
    activatedAt: "2026-04-23 14:50:10",
    completedAt: "2026-04-23 14:52:08",
    definitionRows: [
      { label: "审批方式", value: "单人审批" },
      { label: "审批人来源", value: "部门经理" },
      { label: "是否自动执行", value: "否" },
    ],
    events: [
      {
        title: "节点进入",
        actor: "系统通知",
        time: "2026-04-23 14:50:10",
        message: "流程流转到经理审批节点。",
      },
      {
        title: "审批通过",
        actor: "李经理",
        time: "2026-04-23 14:52:08",
        message: "同意进入财务复核。",
      },
    ],
  },
  Gateway_Result: {
    nodeId: "Gateway_Result",
    nodeName: "是否通过",
    nodeTypeLabel: "排他网关",
    runtimeStateLabel: "已判断",
    runtimeStateClass: "is-completed",
    ownerLabel: "系统",
    activatedAt: "2026-04-23 14:52:09",
    completedAt: "2026-04-23 14:52:09",
    definitionRows: [
      { label: "分支规则", value: "通过流转财务，驳回流转结束" },
      { label: "当前分支", value: "通过" },
    ],
    events: [
      {
        title: "网关判定",
        actor: "系统通知",
        time: "2026-04-23 14:52:09",
        message: "根据经理审批结果，命中“通过”分支。",
      },
    ],
  },
  Task_Finance: {
    nodeId: "Task_Finance",
    nodeName: "财务复核",
    nodeTypeLabel: "人工审批",
    runtimeStateLabel: "待处理",
    runtimeStateClass: "is-running",
    ownerLabel: "张三",
    activatedAt: "2026-04-23 15:10:12",
    completedAt: "-",
    definitionRows: [
      { label: "审批方式", value: "单人审批" },
      { label: "审批人来源", value: "财务专员" },
      { label: "允许退回", value: "是" },
    ],
    events: [
      {
        title: "节点进入",
        actor: "系统通知",
        time: "2026-04-23 15:10:12",
        message: "流程已流转至财务复核，等待张三处理。",
      },
      {
        title: "待办生成",
        actor: "系统通知",
        time: "2026-04-23 15:10:13",
        message: "已创建财务复核待办。",
      },
    ],
  },
  EndEvent_Done: {
    nodeId: "EndEvent_Done",
    nodeName: "完成",
    nodeTypeLabel: "结束事件",
    runtimeStateLabel: "未到达",
    runtimeStateClass: "is-muted",
    ownerLabel: "-",
    activatedAt: "-",
    completedAt: "-",
    definitionRows: [
      { label: "结束语义", value: "审批流程正常完结" },
    ],
    events: [],
  },
  EndEvent_Rejected: {
    nodeId: "EndEvent_Rejected",
    nodeName: "退回",
    nodeTypeLabel: "结束事件",
    runtimeStateLabel: "未到达",
    runtimeStateClass: "is-muted",
    ownerLabel: "-",
    activatedAt: "-",
    completedAt: "-",
    definitionRows: [
      { label: "结束语义", value: "审批被驳回后流程结束" },
    ],
    events: [],
  },
};

export const trackingScenarios = {
  running: {
    key: "running",
    xml: approvalDemoXml,
    title: "销售订单打印审批",
    documentLabel: "S00013",
    triggerLabel: "申请打印",
    stateLabel: "进行中",
    stateClass: "is-running",
    autoStatus: "",
    exceptionMessage: "",
    defaultNodeId: "Task_Finance",
    markers: {
      completed: ["StartEvent_Submit", "Task_Manager", "Gateway_Result"],
      current: ["Task_Finance"],
      pending: ["EndEvent_Done"],
      error: [],
    },
    logs: [
      {
        type: "action",
        actor: "张三",
        time: "2026-04-23 15:10:12",
        title: "当前节点：财务复核",
        message: "等待当前处理人继续审批。",
      },
      {
        type: "passed",
        actor: "李经理",
        time: "2026-04-23 14:52:08",
        title: "已同意",
        message: "经理审批已通过，流程流转至财务节点。",
      },
      {
        type: "sys",
        actor: "系统通知",
        time: "2026-04-23 14:50:01",
        title: "流程启动",
        message: "由按钮“申请打印”触发审批流程。",
      },
    ],
    nodeDetails: {
      ...baseNodeDetails,
    },
  },
  exception: {
    key: "exception",
    xml: approvalDemoXml,
    title: "自动建账抛单流",
    documentLabel: "S00013",
    triggerLabel: "确认销售",
    stateLabel: "系统异常",
    stateClass: "is-exception",
    autoStatus: "自动执行失败待接管",
    exceptionMessage: "ERP 接口连接超时，当前流程已挂起。请回到业务单据执行人工接管。",
    defaultNodeId: "Gateway_Result",
    markers: {
      completed: ["StartEvent_Submit", "Task_Manager"],
      current: [],
      pending: ["Task_Finance", "EndEvent_Done"],
      error: ["Gateway_Result"],
    },
    logs: [
      {
        type: "exception",
        actor: "系统自动执行",
        time: "2026-04-23 16:20:33",
        title: "执行失败",
        message: "自动过账节点执行失败，等待人工接管。",
      },
      {
        type: "passed",
        actor: "自动校验",
        time: "2026-04-23 16:20:15",
        title: "检查通过",
        message: "前置校验完成，进入自动执行阶段。",
      },
      {
        type: "sys",
        actor: "系统通知",
        time: "2026-04-23 16:20:00",
        title: "流程启动",
        message: "由按钮“确认销售”触发自动执行流程。",
      },
    ],
    nodeDetails: {
      ...baseNodeDetails,
      Gateway_Result: {
        nodeId: "Gateway_Result",
        nodeName: "自动过账结果",
        nodeTypeLabel: "异常网关",
        runtimeStateLabel: "异常挂起",
        runtimeStateClass: "is-exception",
        ownerLabel: "系统自动执行",
        activatedAt: "2026-04-23 16:20:15",
        completedAt: "-",
        definitionRows: [
          { label: "节点模式", value: "自动执行 + 错误挂起" },
          { label: "人工接管", value: "允许" },
          { label: "错误来源", value: "ERP 接口超时" },
        ],
        events: [
          {
            title: "进入自动执行",
            actor: "系统通知",
            time: "2026-04-23 16:20:15",
            message: "前置审批已完成，开始自动过账。",
          },
          {
            title: "执行失败",
            actor: "系统自动执行",
            time: "2026-04-23 16:20:33",
            message: "ERP 接口连接超时，节点进入挂起状态。",
          },
        ],
      },
      Task_Finance: {
        nodeId: "Task_Finance",
        nodeName: "财务复核",
        nodeTypeLabel: "人工审批",
        runtimeStateLabel: "尚未激活",
        runtimeStateClass: "is-muted",
        ownerLabel: "待定",
        activatedAt: "-",
        completedAt: "-",
        definitionRows: [
          { label: "审批方式", value: "单人审批" },
          { label: "审批人来源", value: "财务专员" },
          { label: "进入条件", value: "自动过账成功后激活" },
        ],
        events: [],
      },
      EndEvent_Done: {
        nodeId: "EndEvent_Done",
        nodeName: "完成",
        nodeTypeLabel: "结束事件",
        runtimeStateLabel: "尚未到达",
        runtimeStateClass: "is-muted",
        ownerLabel: "-",
        activatedAt: "-",
        completedAt: "-",
        definitionRows: [
          { label: "结束语义", value: "自动执行成功后正常结束" },
        ],
        events: [],
      },
    },
  },
};
