export const baseNodeDetails = {
  StartEvent_Submit: {
    nodeId: "StartEvent_Submit",
    nodeName: "提交申请",
    nodeTypeLabel: "开始事件",
    runtimeStateLabel: "已完成",
    runtimeStateClass: "is-completed",
    ownerLabel: "系统",
    activatedAt: "2026-04-23 14:50:01",
    completedAt: "2026-04-23 14:50:01",
    definitionRows: [
      { label: "触发方式", value: "按钮触发" },
      { label: "按钮来源", value: "申请打印" },
    ],
    events: [
      {
        title: "流程启动",
        actor: "系统通知",
        time: "2026-04-23 14:50:01",
        message: "由业务按钮触发流程实例创建。",
      },
    ],
  },
  Task_Manager: {
    nodeId: "Task_Manager",
    nodeName: "经理审批",
    nodeTypeLabel: "人工审批",
    runtimeStateLabel: "已完成",
    runtimeStateClass: "is-completed",
    ownerLabel: "李经理",
    activatedAt: "2026-04-23 14:50:10",
    completedAt: "2026-04-23 14:52:08",
    definitionRows: [
      { label: "审批方式", value: "单人审批" },
      { label: "审批人来源", value: "部门经理" },
      { label: "是否自动执行", value: "否" },
    ],
    events: [
      {
        title: "节点进入",
        actor: "系统通知",
        time: "2026-04-23 14:50:10",
        message: "流程流转到经理审批节点。",
      },
      {
        title: "审批通过",
        actor: "李经理",
        time: "2026-04-23 14:52:08",
        message: "同意进入财务复核。",
      },
    ],
  },
  Gateway_Result: {
    nodeId: "Gateway_Result",
    nodeName: "是否通过",
    nodeTypeLabel: "排他网关",
    runtimeStateLabel: "已判断",
    runtimeStateClass: "is-completed",
    ownerLabel: "系统",
    activatedAt: "2026-04-23 14:52:09",
    completedAt: "2026-04-23 14:52:09",
    definitionRows: [
      { label: "分支规则", value: "通过流转财务，驳回流转结束" },
      { label: "当前分支", value: "通过" },
    ],
    events: [
      {
        title: "网关判定",
        actor: "系统通知",
        time: "2026-04-23 14:52:09",
        message: "根据经理审批结果，命中“通过”分支。",
      },
    ],
  },
  Task_Finance: {
    nodeId: "Task_Finance",
    nodeName: "财务复核",
    nodeTypeLabel: "人工审批",
    runtimeStateLabel: "待处理",
    runtimeStateClass: "is-running",
    ownerLabel: "张三",
    activatedAt: "2026-04-23 15:10:12",
    completedAt: "-",
    definitionRows: [
      { label: "审批方式", value: "单人审批" },
      { label: "审批人来源", value: "财务专员" },
      { label: "允许退回", value: "是" },
    ],
    events: [
      {
        title: "节点进入",
        actor: "系统通知",
        time: "2026-04-23 15:10:12",
        message: "流程已流转至财务复核，等待张三处理。",
      },
      {
        title: "待办生成",
        actor: "系统通知",
        time: "2026-04-23 15:10:13",
        message: "已创建财务复核待办。",
      },
    ],
  },
  EndEvent_Done: {
    nodeId: "EndEvent_Done",
    nodeName: "完成",
    nodeTypeLabel: "结束事件",
    runtimeStateLabel: "未到达",
    runtimeStateClass: "is-muted",
    ownerLabel: "-",
    activatedAt: "-",
    completedAt: "-",
    definitionRows: [
      { label: "结束语义", value: "审批流程正常完结" },
    ],
    events: [],
  },
  EndEvent_Rejected: {
    nodeId: "EndEvent_Rejected",
    nodeName: "退回",
    nodeTypeLabel: "结束事件",
    runtimeStateLabel: "未到达",
    runtimeStateClass: "is-muted",
    ownerLabel: "-",
    activatedAt: "-",
    completedAt: "-",
    definitionRows: [
      { label: "结束语义", value: "审批被驳回后流程结束" },
    ],
    events: [],
  },
};
