function entry(id, type, icon, label, options = {}) {
  return {
    id,
    type,
    icon,
    label,
    options,
  };
}

export const paletteGroups = [
  {
    id: "start-event",
    title: "Start",
    entries: [
      entry("create.start.none", "bpmn:StartEvent", "bpmn-icon-start-event-none", "Start"),
      entry("create.start.message", "bpmn:StartEvent", "bpmn-icon-start-event-message", "Msg Start", { eventDefinitionType: "bpmn:MessageEventDefinition" }),
      entry("create.start.timer", "bpmn:StartEvent", "bpmn-icon-start-event-timer", "Timer Start", { eventDefinitionType: "bpmn:TimerEventDefinition" }),
      entry("create.start.condition", "bpmn:StartEvent", "bpmn-icon-start-event-condition", "Cond Start", { eventDefinitionType: "bpmn:ConditionalEventDefinition" }),
      entry("create.start.signal", "bpmn:StartEvent", "bpmn-icon-start-event-signal", "Signal Start", { eventDefinitionType: "bpmn:SignalEventDefinition" }),
    ],
  },
  {
    id: "event-subprocess-start",
    title: "Event Starts",
    entries: [
      entry("create.event-subprocess-start.message", "bpmn:StartEvent", "bpmn-icon-start-event-message", "Int Msg", { eventDefinitionType: "bpmn:MessageEventDefinition", isInterrupting: true }),
      entry("create.event-subprocess-start.timer", "bpmn:StartEvent", "bpmn-icon-start-event-timer", "Int Timer", { eventDefinitionType: "bpmn:TimerEventDefinition", isInterrupting: true }),
      entry("create.event-subprocess-start.condition", "bpmn:StartEvent", "bpmn-icon-start-event-condition", "Int Cond", { eventDefinitionType: "bpmn:ConditionalEventDefinition", isInterrupting: true }),
      entry("create.event-subprocess-start.signal", "bpmn:StartEvent", "bpmn-icon-start-event-signal", "Int Signal", { eventDefinitionType: "bpmn:SignalEventDefinition", isInterrupting: true }),
      entry("create.event-subprocess-start.error", "bpmn:StartEvent", "bpmn-icon-start-event-error", "Int Error", { eventDefinitionType: "bpmn:ErrorEventDefinition", isInterrupting: true }),
      entry("create.event-subprocess-start.escalation", "bpmn:StartEvent", "bpmn-icon-start-event-escalation", "Int Esc", { eventDefinitionType: "bpmn:EscalationEventDefinition", isInterrupting: true }),
      entry("create.event-subprocess-start.compensation", "bpmn:StartEvent", "bpmn-icon-start-event-compensation", "Int Comp", { eventDefinitionType: "bpmn:CompensateEventDefinition", isInterrupting: true }),
      entry("create.event-subprocess-start.non-interrupting-message", "bpmn:StartEvent", "bpmn-icon-start-event-non-interrupting-message", "Non Msg", { eventDefinitionType: "bpmn:MessageEventDefinition", isInterrupting: false }),
      entry("create.event-subprocess-start.non-interrupting-timer", "bpmn:StartEvent", "bpmn-icon-start-event-non-interrupting-timer", "Non Timer", { eventDefinitionType: "bpmn:TimerEventDefinition", isInterrupting: false }),
      entry("create.event-subprocess-start.non-interrupting-condition", "bpmn:StartEvent", "bpmn-icon-start-event-non-interrupting-condition", "Non Cond", { eventDefinitionType: "bpmn:ConditionalEventDefinition", isInterrupting: false }),
      entry("create.event-subprocess-start.non-interrupting-signal", "bpmn:StartEvent", "bpmn-icon-start-event-non-interrupting-signal", "Non Signal", { eventDefinitionType: "bpmn:SignalEventDefinition", isInterrupting: false }),
      entry("create.event-subprocess-start.non-interrupting-escalation", "bpmn:StartEvent", "bpmn-icon-start-event-non-interrupting-escalation", "Non Esc", { eventDefinitionType: "bpmn:EscalationEventDefinition", isInterrupting: false }),
    ],
  },
  {
    id: "intermediate-event",
    title: "Middle Events",
    entries: [
      entry("create.intermediate.none", "bpmn:IntermediateThrowEvent", "bpmn-icon-intermediate-event-none", "Throw"),
      entry("create.intermediate.message-catch", "bpmn:IntermediateCatchEvent", "bpmn-icon-intermediate-event-catch-message", "Msg Catch", { eventDefinitionType: "bpmn:MessageEventDefinition" }),
      entry("create.intermediate.message-throw", "bpmn:IntermediateThrowEvent", "bpmn-icon-intermediate-event-throw-message", "Msg Throw", { eventDefinitionType: "bpmn:MessageEventDefinition" }),
      entry("create.intermediate.timer-catch", "bpmn:IntermediateCatchEvent", "bpmn-icon-intermediate-event-catch-timer", "Timer Catch", { eventDefinitionType: "bpmn:TimerEventDefinition" }),
      entry("create.intermediate.escalation-throw", "bpmn:IntermediateThrowEvent", "bpmn-icon-intermediate-event-throw-escalation", "Esc Throw", { eventDefinitionType: "bpmn:EscalationEventDefinition" }),
      entry("create.intermediate.condition-catch", "bpmn:IntermediateCatchEvent", "bpmn-icon-intermediate-event-catch-condition", "Cond Catch", { eventDefinitionType: "bpmn:ConditionalEventDefinition" }),
      entry("create.intermediate.link-catch", "bpmn:IntermediateCatchEvent", "bpmn-icon-intermediate-event-catch-link", "Link Catch", { eventDefinitionType: "bpmn:LinkEventDefinition", eventDefinitionAttrs: { name: "" } }),
      entry("create.intermediate.link-throw", "bpmn:IntermediateThrowEvent", "bpmn-icon-intermediate-event-throw-link", "Link Throw", { eventDefinitionType: "bpmn:LinkEventDefinition", eventDefinitionAttrs: { name: "" } }),
      entry("create.intermediate.compensation-throw", "bpmn:IntermediateThrowEvent", "bpmn-icon-intermediate-event-throw-compensation", "Comp Throw", { eventDefinitionType: "bpmn:CompensateEventDefinition" }),
      entry("create.intermediate.signal-catch", "bpmn:IntermediateCatchEvent", "bpmn-icon-intermediate-event-catch-signal", "Signal Catch", { eventDefinitionType: "bpmn:SignalEventDefinition" }),
      entry("create.intermediate.signal-throw", "bpmn:IntermediateThrowEvent", "bpmn-icon-intermediate-event-throw-signal", "Signal Throw", { eventDefinitionType: "bpmn:SignalEventDefinition" }),
    ],
  },
  {
    id: "boundary",
    title: "Boundary",
    entries: [
      entry("create.boundary.message", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-message", "Bnd Msg", { eventDefinitionType: "bpmn:MessageEventDefinition", cancelActivity: true }),
      entry("create.boundary.timer", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-timer", "Bnd Timer", { eventDefinitionType: "bpmn:TimerEventDefinition", cancelActivity: true }),
      entry("create.boundary.escalation", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-escalation", "Bnd Esc", { eventDefinitionType: "bpmn:EscalationEventDefinition", cancelActivity: true }),
      entry("create.boundary.condition", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-condition", "Bnd Cond", { eventDefinitionType: "bpmn:ConditionalEventDefinition", cancelActivity: true }),
      entry("create.boundary.error", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-error", "Bnd Error", { eventDefinitionType: "bpmn:ErrorEventDefinition", cancelActivity: true }),
      entry("create.boundary.cancel", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-cancel", "Bnd Cancel", { eventDefinitionType: "bpmn:CancelEventDefinition", cancelActivity: true }),
      entry("create.boundary.signal", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-signal", "Bnd Signal", { eventDefinitionType: "bpmn:SignalEventDefinition", cancelActivity: true }),
      entry("create.boundary.compensation", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-compensation", "Bnd Comp", { eventDefinitionType: "bpmn:CompensateEventDefinition", cancelActivity: true }),
      entry("create.boundary.non-interrupting-message", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-non-interrupting-message", "Non Msg", { eventDefinitionType: "bpmn:MessageEventDefinition", cancelActivity: false }),
      entry("create.boundary.non-interrupting-timer", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-non-interrupting-timer", "Non Timer", { eventDefinitionType: "bpmn:TimerEventDefinition", cancelActivity: false }),
      entry("create.boundary.non-interrupting-escalation", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-non-interrupting-escalation", "Non Esc", { eventDefinitionType: "bpmn:EscalationEventDefinition", cancelActivity: false }),
      entry("create.boundary.non-interrupting-condition", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-non-interrupting-condition", "Non Cond", { eventDefinitionType: "bpmn:ConditionalEventDefinition", cancelActivity: false }),
      entry("create.boundary.non-interrupting-signal", "bpmn:BoundaryEvent", "bpmn-icon-intermediate-event-catch-non-interrupting-signal", "Non Signal", { eventDefinitionType: "bpmn:SignalEventDefinition", cancelActivity: false }),
    ],
  },
  {
    id: "end-event",
    title: "End",
    entries: [
      entry("create.end.none", "bpmn:EndEvent", "bpmn-icon-end-event-none", "End"),
      entry("create.end.message", "bpmn:EndEvent", "bpmn-icon-end-event-message", "Msg End", { eventDefinitionType: "bpmn:MessageEventDefinition" }),
      entry("create.end.escalation", "bpmn:EndEvent", "bpmn-icon-end-event-escalation", "Esc End", { eventDefinitionType: "bpmn:EscalationEventDefinition" }),
      entry("create.end.error", "bpmn:EndEvent", "bpmn-icon-end-event-error", "Error End", { eventDefinitionType: "bpmn:ErrorEventDefinition" }),
      entry("create.end.cancel", "bpmn:EndEvent", "bpmn-icon-end-event-cancel", "Cancel End", { eventDefinitionType: "bpmn:CancelEventDefinition" }),
      entry("create.end.compensation", "bpmn:EndEvent", "bpmn-icon-end-event-compensation", "Comp End", { eventDefinitionType: "bpmn:CompensateEventDefinition" }),
      entry("create.end.signal", "bpmn:EndEvent", "bpmn-icon-end-event-signal", "Signal End", { eventDefinitionType: "bpmn:SignalEventDefinition" }),
      entry("create.end.terminate", "bpmn:EndEvent", "bpmn-icon-end-event-terminate", "Term End", { eventDefinitionType: "bpmn:TerminateEventDefinition" }),
    ],
  },
  {
    id: "task",
    title: "Tasks",
    entries: [
      entry("create.task", "bpmn:Task", "bpmn-icon-task", "Task"),
      entry("create.user-task", "bpmn:UserTask", "bpmn-icon-user", "User"),
      entry("create.service-task", "bpmn:ServiceTask", "bpmn-icon-service", "Service"),
      entry("create.send-task", "bpmn:SendTask", "bpmn-icon-send-task", "Send"),
      entry("create.receive-task", "bpmn:ReceiveTask", "bpmn-icon-receive-task", "Receive"),
      entry("create.manual-task", "bpmn:ManualTask", "bpmn-icon-manual", "Manual"),
      entry("create.business-rule-task", "bpmn:BusinessRuleTask", "bpmn-icon-business-rule", "Rule"),
      entry("create.script-task", "bpmn:ScriptTask", "bpmn-icon-script", "Script"),
    ],
  },
  {
    id: "gateway",
    title: "Gateways",
    entries: [
      entry("create.exclusive-gateway", "bpmn:ExclusiveGateway", "bpmn-icon-gateway-xor", "Exclusive"),
      entry("create.parallel-gateway", "bpmn:ParallelGateway", "bpmn-icon-gateway-parallel", "Parallel"),
      entry("create.inclusive-gateway", "bpmn:InclusiveGateway", "bpmn-icon-gateway-or", "Inclusive"),
      entry("create.event-gateway", "bpmn:EventBasedGateway", "bpmn-icon-gateway-eventbased", "Event"),
      entry("create.complex-gateway", "bpmn:ComplexGateway", "bpmn-icon-gateway-complex", "Complex"),
    ],
  },
  {
    id: "container",
    title: "Containers",
    entries: [
      entry("create.subprocess", "bpmn:SubProcess", "bpmn-icon-subprocess-collapsed", "Subprocess"),
      entry("create.expanded-subprocess", "bpmn:SubProcess", "bpmn-icon-subprocess-expanded", "Expanded", { isExpanded: true }),
      entry("create.ad-hoc-subprocess", "bpmn:AdHocSubProcess", "bpmn-icon-subprocess-collapsed", "Ad-hoc", { isExpanded: false }),
      entry("create.expanded-ad-hoc-subprocess", "bpmn:AdHocSubProcess", "bpmn-icon-subprocess-expanded", "Ad-hoc Exp", { isExpanded: true }),
      entry("create.transaction", "bpmn:Transaction", "bpmn-icon-transaction", "Transaction", { isExpanded: true }),
      entry("create.event-subprocess", "bpmn:SubProcess", "bpmn-icon-event-subprocess-expanded", "Event Sub", { triggeredByEvent: true, isExpanded: true }),
      entry("create.call-activity", "bpmn:CallActivity", "bpmn-icon-call-activity", "Call"),
      entry("create.participant.expanded", "bpmn:Participant", "bpmn-icon-participant", "Pool", { isExpanded: true }),
      entry("create.participant.collapsed", "bpmn:Participant", "bpmn-icon-lane", "Pool Empty", { isExpanded: false }),
    ],
  },
  {
    id: "artifact",
    title: "Data / Artifacts",
    entries: [
      entry("create.data-object", "bpmn:DataObjectReference", "bpmn-icon-data-object", "Data"),
      entry("create.data-store", "bpmn:DataStoreReference", "bpmn-icon-data-store", "Store"),
      entry("create.text-annotation", "bpmn:TextAnnotation", "bpmn-icon-text-annotation", "Annotation"),
      entry("create.group", "bpmn:Group", "bpmn-icon-group", "Group"),
    ],
  },
];
